#+TITLE: MECH 306 Tutorial 1:
#+SUBTITLE: Analysis and Graphical Representation of Data

#+LATEX_HEADER: \definecolor{bg}{rgb}{0.95,0.95,0.95}
#+LATEX_HEADER: \setminted{frame=single,bgcolor=bg,samepage=true}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{svg}

* Histogram Exercise
** Importing the data
For the sake of brevity, I have exported the initial ~BoltData~ variable to a separate file.

Let's import it first.
#+BEGIN_SRC matlab :session :exports code :results none

load('boltdata');

#+END_SRC

We can check that the data loaded correctly by checking its size.
#+BEGIN_SRC matlab :session :exports both :results code

ans = size(BoltData)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| 91 | 3 |
#+END_SRC

#+RESULTS:



** Removing incorrect results
Now that the data has been imported into MATLAB, we can start removing invalid data from our analysis.

*** Invalid bolt numbers
There were only 12 types of bolts handed out during the experiment, and the only valid bolt ID numbers are integers from 1-12

Let's use a new variable to hold our cleaned data set.
#+BEGIN_SRC matlab :session :exports code :results none

cleanBoltData = BoltData;

#+END_SRC

Now we create a test for rows of that match our criteria
#+BEGIN_SRC matlab :session :exports code :results none

% Create a column vector for every row in cleanBoltData such that
% rows where the first item is an integer between 1 and 12 are
% equal to one, and zero otherwise
filter = cleanBoltData(:,1) >= 1 & cleanBoltData(:,1) <=12 ...
         & mod(cleanBoltData(:,1),1) == 0;

#+END_SRC

With this filter we can remove unwanted rows from our data.
#+BEGIN_SRC matlab :session :exports code :results none

% Select all rows in cleanBoltData where the corresponding value in filter is one
cleanBoltData = cleanBoltData(filter,:);

#+END_SRC

We can double check that rows have been removed by checking the size again

#+BEGIN_SRC matlab :session :exports both :results code

ans = size(cleanBoltData)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| 88 | 3 |
#+END_SRC

#+RESULTS:

*** Removing unreasonable lengths
According to the tutorial instructions reasonable bolt length measurements should be between 72 and 115 millimetres, so we remove any values outside of that range.

#+BEGIN_SRC matlab :session :exports code :results none

filter = cleanBoltData(:,2) >= 72 & cleanBoltData(:,2) <= 115;
cleanBoltData = cleanBoltData(filter,:);

#+END_SRC

Again we can double check that rows have been removed by checking the size again

#+BEGIN_SRC matlab :session :exports both :results code

ans = size(cleanBoltData)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| 72 | 3 |
#+END_SRC

#+RESULTS:

*** Removing unreasonable diameters
According to the tutorial instructions reasonable bolt diameter measurements should be between 12 and 16 millimetres, so we remove any values outside of that range.

#+BEGIN_SRC matlab :session :exports code :results none

filter = cleanBoltData(:,3) >= 12 & cleanBoltData(:,3) <= 16;
cleanBoltData = cleanBoltData(filter,:);

#+END_SRC

Again we can double check that rows have been removed by checking the size again

#+BEGIN_SRC matlab :session :exports both :results code

ans = size(cleanBoltData)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| 61 | 3 |
#+END_SRC

#+RESULTS:

*** Further removing outliers
Now that the obvious outliers have been removed we can graph the histograms for the bolt length and diameter
#+BEGIN_SRC matlab :session :exports both :results file
name = 'initiallen.svg';
% need many bins because of bimodal distribution
histogram(cleanBoltData(:,2),40); 
title('Bolt Length')
xlabel('Bolt Length, mm')
ylabel('Number of Bolts')

set(gcf, 'PaperUnits', 'inches', 'PaperPosition', [0 0 7 5])

saveas(gcf, name)
ans = name

#+END_SRC

#+ATTR_LaTeX: :placement [H]
#+CAPTION: Histogram of bolt length after removing most of the invalid data label:len1 
#+RESULTS:
[[file:initiallen.svg]]

#+BEGIN_SRC matlab :session :exports both :results file
name = 'initialdia.svg';
histogram(cleanBoltData(:,3),8);
title('Bolt Diameter')
xlabel('Bolt Diameter, mm')
ylabel('Number of Bolts')

set(gcf, 'PaperUnits', 'inches', 'PaperPosition', [0 0 7 5])

saveas(gcf, name)
ans = name

#+END_SRC

#+ATTR_LaTeX: :placement [H]
#+CAPTION: Histogram of bolt diameters after removing most of the invalid data 
#+RESULTS:
[[file:initialdia.svg]]


From Figure ref:len1 it appears that there are still outliers in the middle of the two peaks.

Let's remove values between 70 and 80 millimetres as well as between 100 and 120 millimetres.
#+BEGIN_SRC matlab :session :exports code :results none

filter = (cleanBoltData(:,2) >= 70 & cleanBoltData(:,2) <= 80) | ...
         (cleanBoltData(:,2) >= 100 & cleanBoltData(:,2) <= 120);
cleanBoltData = cleanBoltData(filter,:);

#+END_SRC
** Final Results
Let's plot the final set of data.
#+BEGIN_SRC matlab :session :exports both :results file
name = 'finallen.svg';
histogram(cleanBoltData(:,2),40);
title('Bolt Length')
xlabel('Bolt Length, mm')
ylabel('Number of Bolts')

set(gcf, 'PaperUnits', 'inches', 'PaperPosition', [0 0 7 5])

saveas(gcf, name)
ans = name

#+END_SRC

#+ATTR_LaTeX: :placement [H]
#+CAPTION: Histogram of bolt lengths after removing all of the invalid data 
#+RESULTS:
[[file:finallen.svg]]

#+BEGIN_SRC matlab :session :exports both :results file
name = 'finaldia.svg';
histogram(cleanBoltData(:,3),8);
title('Bolt Diameter')
xlabel('Bolt Diameter, mm')
ylabel('Number of Bolts')

set(gcf, 'PaperUnits', 'inches', 'PaperPosition', [0 0 7 5])

saveas(gcf, name)
ans = name

#+END_SRC

#+ATTR_LaTeX: :placement [H]
#+CAPTION: Histogram of bolt diameters after removing all of the invalid data 
#+RESULTS:
[[file:finaldia.svg]]

Let's also grab the averages and standard deviations for the bolt lengths and diameters.

#+BEGIN_SRC matlab :session :results code :exports both
% sort data into two length groups
iL1 = 0;
iL2 = 0;
for i = 1:1:size(cleanBoltData,1)
    if cleanBoltData(i,2)>=71 && cleanBoltData(i,2)<=78
        iL1 = iL1+1;
        LengthData1(iL1) = cleanBoltData(i,2);
    elseif cleanBoltData(i,2)>=108 && cleanBoltData(i,2)<=115
        iL2 = iL2+1;
        LengthData2(iL2) = cleanBoltData(i,2);
    end
end

% Find average and standard deviation of each bolt length
LengthAvg = [mean(LengthData1) mean(LengthData2)];
LengthStd = [ std(LengthData1)  std(LengthData2)];

% sort data into two diameter groups
iD1 = 0;
iD2 = 0;
for i = 1:1:size(cleanBoltData,1)
    if cleanBoltData(i,3)>=12 && cleanBoltData(i,3)<=14
        iD1 = iD1+1;
        DiamData1(iD1) = cleanBoltData(i,3);
    elseif cleanBoltData(i,3)>14 && cleanBoltData(i,3)<=16
        iD2 = iD2+1;
        DiamData2(iD2) = cleanBoltData(i,3);
    end
end

% Find average and standard deviation of each bolt diameter
DiamAvg = [mean(DiamData1) mean(DiamData2)];
DiamStd = [ std(DiamData1)  std(DiamData2)];

len_avg = sprintf('LengthAvg %f %f', LengthAvg(:));
len_std = sprintf('LengthStd %f %f', LengthStd(:));

dia_avg = sprintf('DiamAvg %f %f', DiamAvg(:));
dia_std = sprintf('DiamStd %f %f', DiamStd(:));

ans = sprintf('%s\n%s\n%s\n%s', len_avg, len_std, dia_avg, dia_std)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| LengthAvg 74.562963 112.631250 |
| LengthStd 0.878000 0.827915    |
| DiamAvg 13.166667 15.073171    |
| DiamStd 0.618347 0.384724      |
#+END_SRC

#+RESULTS:

* Box Plot exercise
** Importing the data
#+BEGIN_SRC matlab :session :exports code :results none

A = [112.5 113 113 113.4 112 112.5 113.5]';
D = [112 112.5 113.5 112.5 113 113 112.5]';
E = [112 112 112.5 113 113.5 113.5 114.3]';
G = [113 111 112 112.5 112.5 110 112.5]';
H = [111.5 112 114 112 112.5 113 112.5]';

all = [A D E G H];
All = reshape(all, [], 1);

#+END_SRC
** Plotting the bolts separately
#+BEGIN_SRC matlab :session :exports both :results file

name = 'boxsep.svg';

boxplot(all, ['A' 'D' 'E' 'G' 'H']')
title('Individual Bolt Lengths')
xlabel('Bolt ID')
ylabel('Bolt Length, mm')

set(gcf, 'PaperUnits', 'inches', 'PaperPosition', [0 0 7 5])

saveas(gcf, name)
ans = name
#+END_SRC

#+ATTR_LaTeX: :placement [H]
#+CAPTION: Box plot of individual bolt lengths using data supplied from tutorial
#+RESULTS:
[[file:boxsep.svg]]

** Plotting the bolts together
#+BEGIN_SRC matlab :session :exports both :results file

name = 'boxtog.svg';

boxplot(All)
title('All Bolt Lengths')
xlabel('All Bolts')
ylabel('Bolt Length, mm')

set(gcf, 'PaperUnits', 'inches', 'PaperPosition', [0 0 7 5])
set(gca, 'XTickLabel', {' '})

saveas(gcf, name)
ans = name
#+END_SRC

#+ATTR_LaTeX: :placement [H]
#+CAPTION: Box plot of all bolt lengths using data supplied from tutorial
#+RESULTS:
[[file:boxtog.svg]]
** Signifcant Statistics
*** Bolt A
#+BEGIN_SRC matlab :session :results code :exports both

mean_A = mean(A);
median_A = median(A);
quartiles_A = quantile(A, [0.25 0.50 0.75]);
stddev_A = std(A);
var_A = var(A);

mean_A_str = sprintf('mean_A: %f', mean_A);
median_A_str = sprintf('median_A: %f', median_A);
quartiles_A_str = sprintf('quartiles_A: %f %f %f', quartiles_A(:));
stddev_A_str = sprintf('stddev_A: %f', stddev_A);
var_A_str = sprintf('var_A: %f', var_A);

ans = sprintf('%s\n%s\n%s\n%s\n%s', ...
              mean_A_str, median_A_str, ...
              quartiles_A_str, stddev_A_str, ...
              var_A_str)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| mean_A: 112.842857                            |
| median_A: 113.000000                          |
| quartiles_A: 112.500000 113.000000 113.300000 |
| stddev_A: 0.538074                            |
| var_A: 0.289524                               |
#+END_SRC

For the sake of brevity only the results will be included in the following secttions

*** Bolt D
#+BEGIN_SRC matlab :session :results code :exports results

mean_D = mean(D);
median_D = median(D);
quartiles_D = quantile(D, [0.25 0.50 0.75]);
stddev_D = std(D);
var_D = var(D);

mean_D_str = sprintf('mean_D: %f', mean_D);
median_D_str = sprintf('median_D: %f', median_D);
quartiles_D_str = sprintf('quartiles_D: %f %f %f', quartiles_D(:));
stddev_D_str = sprintf('stddev_D: %f', stddev_D);
var_D_str = sprintf('var_D: %f', var_D);

ans = sprintf('%s\n%s\n%s\n%s\n%s', ...
              mean_D_str, median_D_str, ...
              quartiles_D_str, stddev_D_str, ...
              var_D_str)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| mean_D: 112.714286                            |
| median_D: 112.500000                          |
| quartiles_D: 112.500000 112.500000 113.000000 |
| stddev_D: 0.487950                            |
| var_D: 0.238095                               |
#+END_SRC

*** Bolt E
#+BEGIN_SRC matlab :session :results code :exports results

mean_E = mean(E);
median_E = median(E);
quartiles_E = quantile(E, [0.25 0.50 0.75]);
stddev_E = std(E);
var_E = var(E);

mean_E_str = sprintf('mean_E: %f', mean_E);
median_E_str = sprintf('median_E: %f', median_E);
quartiles_E_str = sprintf('quartiles_E: %f %f %f', quartiles_E(:));
stddev_E_str = sprintf('stddev_E: %f', stddev_E);
var_E_str = sprintf('var_E: %f', var_E);

ans = sprintf('%s\n%s\n%s\n%s\n%s', ...
              mean_D_str, median_D_str, ...
              quartiles_D_str, stddev_D_str, ...
              var_D_str)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| mean_E: 112.971429                            |
| median_E: 113.000000                          |
| quartiles_E: 112.125000 113.000000 113.500000 |
| stddev_E: 0.859679                            |
| var_E: 0.739048                               |
#+END_SRC
*** Bolt G
#+BEGIN_SRC matlab :session :results code :exports results

mean_G = mean(G);
median_G = median(G);
quartiles_G = quantile(G, [0.25 0.50 0.75]);
stddev_G = std(G);
var_G = var(G);

mean_G_str = sprintf('mean_G: %f', mean_G);
median_G_str = sprintf('median_G: %f', median_G);
quartiles_G_str = sprintf('quartiles_G: %f %f %f', quartiles_G(:));
stddev_G_str = sprintf('stddev_G: %f', stddev_G);
var_G_str = sprintf('var_G: %f', var_G);

ans = sprintf('%s\n%s\n%s\n%s\n%s', ...
              mean_G_str, median_G_str, ...
              quartiles_G_str, stddev_G_str, ...
              var_G_str)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| mean_G: 111.928571                            |
| median_G: 112.500000                          |
| quartiles_G: 111.250000 112.500000 112.500000 |
| stddev_G: 1.057850                            |
| var_G: 1.119048                               |
#+END_SRC
*** Bolt H
#+BEGIN_SRC matlab :session :results code :exports results

mean_H = mean(H);
median_H = median(H);
quartiles_H = quantile(H, [0.25 0.50 0.75]);
stddev_H = std(H);
var_H = var(H);

mean_H_str = sprintf('mean_H: %f', mean_H);
median_H_str = sprintf('median_H: %f', median_H);
quartiles_H_str = sprintf('quartiles_H: %f %f %f', quartiles_H(:));
stddev_H_str = sprintf('stddev_H: %f', stddev_H);
var_H_str = sprintf('var_H: %f', var_H);

ans = sprintf('%s\n%s\n%s\n%s\n%s', ...
              mean_H_str, median_H_str, ...
              quartiles_H_str, stddev_H_str, ...
              var_H_str)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| mean_H: 112.500000                            |
| median_H: 112.500000                          |
| quartiles_H: 112.000000 112.500000 112.875000 |
| stddev_H: 0.816497                            |
| var_H: 0.666667                               |
#+END_SRC
*** All bolts
#+BEGIN_SRC matlab :session :results code :exports results

mean_All = mean(All);
median_All = median(All);
quartiles_All = quantile(All, [0.25 0.50 0.75]);
stddev_All = std(All);
var_All = var(All);

mean_All_str = sprintf('mean_All: %f', mean_All);
median_All_str = sprintf('median_All: %f', median_All);
quartiles_All_str = sprintf('quartiles_All: %f %f %f', quartiles_All(:));
stddev_All_str = sprintf('stddev_All: %f', stddev_All);
var_All_str = sprintf('var_All: %f', var_All);

ans = sprintf('%s\n%s\n%s\n%s\n%s', ...
              mean_All_str, median_All_str, ...
              quartiles_All_str, stddev_All_str, ...
              var_All_str)

#+END_SRC

#+RESULTS:
#+BEGIN_SRC matlab
| mean_All: 112.591429                            |
| median_All: 112.500000                          |
| quartiles_All: 112.000000 112.500000 113.000000 |
| stddev_All: 0.822611                            |
| var_All: 0.676689                               |
#+END_SRC
* Conclusion
Raw data (especially crowd sourced data) is often not in the format you want.
Because of this it is hard to be confident on the veracity of any specific data point, even ignoring ones that are obviously wrong.

Using software to do data analysis can be very convenient, but adds another layer to the process that can cause hard to find errors (i.e. deleting valid data or not deleting invalid data).
It is very important to double check any code that is used in data analysis
